columns : 
  longitude : float64
  latitude : float64
  housing_median_age : float64
  total_rooms : float64
  total_bedrooms : float64
  population : float64
  households : float64
  median_income : float64
  median_house_value : float64
  ocean_proximity : object

target_columns : median_house_value

domain_value:
  ocean_proximity:
    - <1H OCEAN 
    - INLAND 
    - ISLAND 
    - NEAR BAY 
    - NEAR OCEAN


numerical_column:
  longitude
  latitude
  housing_median_age
  total_rooms
  total_bedrooms
  population
  households 
  median_income

categorical_column:
  ocean_proximity